[package]
name = "nrf54l15-flpr-pac"
version = "0.1.0"
edition = "2024"

[dependencies]
critical-section = { version = "1.0", optional = true }
riscv = "0.15.0"
riscv-rt = { version = "0.16.0", optional = true }
vcell = "0.1.0"

[features]
rt = ["riscv-rt"]
